### ISSUE TITLE
Dropdown list in frmProduct to chose Category

### ISSUE THREAD

**Issue by rubberydev** [Fenglerboix/SalesFinallyProject#13]
This dropdownlist must load when the user choose the category of product in the form register product...So, automatically should load a list of product that has a relationship in the database of one to many, where CategoryID is primary key in table Category and Foreign key in product.

Example Category 
Articles:
-Sunglasses
-watchs
-caps
-jewel

Clothes
-Jean
-Tshirt
-skirt
-cout
-dress
-pants

Shoes:
-runners
-sandals
-boots

**Comment by lramirezsuarez** [comment]
Voy a crear estas categorias Julian. Sencillas para no complicarnos mucho, y teniendo en cuenta que es de deportes hay algunas de las categorias que pusiste que no aplican mucho:
Id: 1 - Nombre Categoria: T-Shirt
Id: 2 - Nombre Categoria: Pants
Id: 3 - Nombre Categoria: Runners
Id: 4 - Nombre Categoria: Accesories
Id: 5 - Nombre Categoria: Protectors

Para que agregues a la base de datos.
Estamos hablando como organizar mejor eso.

**Comment by lramirezsuarez** [comment]
Me queda una duda que seria para corregir, ya tengo una idea de como hacerlo, pero demora un poco mas. El nombre de la categoria deberia cogerlo con otro select con el categID, lo otro es que tenemos que agregar un formulario pequeño si queremos agregar una nueva categoria.
Tambien en el listar productos para el SectionMain, la consulta deberia tener inner join, para coger el nombre de la categoria usando el categID del producto como tal.
De todo esto ya tengo una idea y lo ire trabajando. Pero la base ya esta y ya funciona sin interactuar con la categoria.

**Comment by rubberydev** [comment]
parce ya mire todo el codigo y se ve muy bien, apenas lo pruebe te comento...pero por lo que alcanzo a deducir desde el codigo todo esta full le estas trabajando duro, muy bien...hubiera sido mejor con ajax y JSON!! consumiria menos recursos en el servidor...pero tambien es valido!!!! 👍

**Comment by lramirezsuarez** [comment]
Pues si, hay muchas cosas que se pueden hacer mejor, pero me parece salirnos del proposito del proyecto que es implementar lo que hicimos en la materia.
Estamos aprendiendo php y mysql, lo del bootstrap y el sweet alert esta bueno para que se vea bonito, pero meterle mas vainas, jquery, angular.. o quien sabe que mas. Cuando no fue algo que hicimos en la materia, me parece un poco salido del tema. Chevere para aprender, y a nosotros nos sirve, pero de pronto es abarcar de mas, innecesariamente.

**Comment by rubberydev** [comment]
Si parce estoy de acuerdo con lo que decis, solo te dije por si no conocias esa tecnica que te menciono, porque es lo que se utiliza en ese tipo de funcionalidades y es muy optimo y facil de hacer.  JSON y Ajax es JavaScript!!!

**Comment by rubberydev** [comment]
Perfecto el ejemplo que pones con Apple yo se que significa trademark por eso lo puse xD,
product name: Iphone 6, que en el caso como registraste las categorias seria el product name...
Trademark: Apple

lo que usted hizo
Category: Runners
Trademark: Nike o Adidas o Converse o Ralph Lauren etc

no seria exactamente lo mismo:
si lee bien el ejemplo del issue ahi si tiene sentido lo que usted dice
Category: Accessories
Product Name: Sunglasses, Caps, gloves, helmets

ahi si aplicaria: por eso puse que cargara todos los productos dependiendo la categoria que escogiera...
pero en fin tenemos logica diferentes,
 Mire el issue cuando lo describo al principio 
Categoria Shoes:
Product name
-runners
-boots
-etc.

Category: Runners
Product name: Runners nike pienselo y decide..

**Comment by lramirezsuarez** [comment]
Ahí es donde no me entendés, que no es por la lógica tuya, ni la mía. Sino que en las tiendas en general, no se maneja trademark, se maneja brand. 
Si fuéramos a manejar la marca, adicional al nombre del producto y la categoría que es algo más general, seria agregarle "Brand", esa seria la palabra. Como lo habías puesto en la descripción lo había entendido como Categoría y subcategoría, están los tennis con subcategoría runners, jumpers o quien sabe que más tipos de tennis. 
Para ni complicar el asunto, por eso yo deje, una categoría general y ya. El nombre del producto con la descripción general, o adicional y como habíamos pensado, cantidad, costo y ya. 
Por eso creo que así como esta, ya esta bien, y agregarle más, ya seria adicional si queremos,pero para el propósito inicial del proyecto ya está listo.

**Comment by rubberydev** [comment]
No problem bro...
