### ISSUE TITLE
Login and Register of Users.

### ISSUE THREAD

**Issue by lramirezsuarez** [Fenglerboix/SalesFinallyProject#2]
Register of user to the database.

**Comment by rubberydev** [comment]
parce tengo un problema con las cookies para mostrar las visitas de cada usuario el bug esta en las lineas del frmRegisterProduct cuando valida el tipo de rol...y muestra las visitas no esta funcionando correctamente, las muestra, pero cuando entra a la validacion de employee no muestra nada y las otras dos que si muestra osea customer y administrator se quedan estaticas las cookies la verdad no se que esta pasando...cuando tengas un tiempo lo miras haber si depronto usted ve el error.

**Comment by rubberydev** [comment]
creo que puede ser porque en mi navegador esas cookies ya estaban declaradas en otro proyecto, podemos intentar cambiando el nombre de las cookies...o limpiar las cookies del navegador porque como te digo puede ser mi navegador porque recuerda que yo tengo un poco de plugin para hacer pentesting y entre uno de tantos tengo algo que bloquea las cookies...podes probarlo en el tuyo haber si te funciona...a lo mejor no es bug porque la verdad no veo el error...entra valida correctamente la variable de sesion...y las cookies ??????

**Comment by lramirezsuarez** [comment]
Solucionado, era otro problema. Toca hacer una variable de session y aumentarla. Ya hice eso, y agregue otras cosas.
Corregi algunas cosas escritas y ya hice merge de esas correcciones. Voy a cerrar este issue, ya podes trabajar en el nuevo.
Recorda que los commits deben ser #2 -Razon del commit.
NO #issue1 -Razon del commit., sino, no queda relacionado con el issue que es, y no muestra los commits donde es.
Ya podes seguir adelantando lo siguiente y me avisas para seguir haciendo cosas yo.

**Comment by rubberydev** [comment]
Excelente lucho...asi es parce!!!! lo de los issue no sabia...ya se para los proximos....Muchas gracias
