### ISSUE TITLE
Update/Modify Products Information.

### ISSUE THREAD

**Issue by lramirezsuarez** [Fenglerboix/SalesFinallyProject#6]
Change the name, quantity, description or cost of a product.

**Comment by rubberydev** [comment]
also I add date of last visit by each user

**Comment by lramirezsuarez** [comment]
There's still problems with the Update, it is sending a lot of non-breaking spacesm and the numeral values in productID, quantity and cost are not displaying for some reason. Trying to correct that.

**Comment by rubberydev** [comment]
yo creo que el update controller y el delete controller se pueden unir solo en el product controller ...yo lo separe para hacer la pruebas pero en vista que ya cuadraste todos los errores que yo tenia...lo podes unir en un solo controlador que es al que pertenece las diferentes acciones del Crud de Product...como trabajando en MVC porque eso es un bug tambien uno no crea un controlador para cada accion...mijo y todas las criticas constructivas bienvenidas a mi me gusta aprender de los errores...me corrige o me dice que no entiende que algo hacemos y aprendemos los dos.

**Comment by lramirezsuarez** [comment]
Claro Julian, esto es para aprender, nada mas. La materia ya la tenemos ganada tambien y no estamos perdidos. Lo que has hecho me ha enseñado mucho a mi, y lo que yo sepa, tambien de una.
Creo que no es pertinente unirlos, porque no siempre estamos haciendo lo mismo, cuando llamamos al productController estamos registrando, cuando llamamos al update estamos actualizando y borrar para otra cosa. Lo otro seria poner una variable bandera para indicar que es lo que estamos haciendo, y ahi si podriamos unir todo a un solo controlador. Que ejecute determinada funcion cuando reciba tal valor de esa variable bandera.
Es una buena idea, pero de pronto podemos dejarlo para mas adelante, primero dejar listo todo lo demas primero.

**Comment by rubberydev** [comment]
excelente lo del delete papa!!!

otro error grande que hay es que yo no e adaptado la app a la nueva estructura de la base de datos...con el script que yo hice...¿todo lo que estas corrigiendo lo estas haciendo en base a la nueva estructura de la base de datos? 

Porque sino despues hay que corregir todo otra vez.

**Comment by rubberydev** [comment]
parce pero como el no nos enseño como hacer una clase en el controlador...por eso no la hicimos asi....pero creo que al estar creando objetos diferentes no hay que hacer lo que usted dice...porque al igual los post se reciben por nombres de  input en formularios diferentes, y la copia de las funciones set y metodos son para objetos diferentes...entonces no tiene porque generar problema..pruebe haber si le da...porque asi es que se trabaja MVC.

y la idea suya esta muy buena parce es una posibilidad tambien, en caso de que falle la solucion que yo le digo que es mas facil de hacer y te ahorra tiempo.

**Comment by lramirezsuarez** [comment]
Ya agregue algunas cosas, pero no he hecho los select para categoria, y necesitamos el customer Id, no se si lo podemos traer de la base de datos, o la misma session nos la da, estoy terminando de resolver estos dias el update para pasar a lo siguiente.
En mi Base de datos yo ya agregue los nuevos campos, tambien en las consultas y la tabla que muestra los productos.

**Comment by rubberydev** [comment]
.Mi pregunta es en lo que estas trabajando y todas las correciones de mi codigo que has hecho, entre esas esta lo del nuevo esquema de base de datos?

lo de las categorias se debe tener en cuenta al momento de hacer el insert...Claro esta, es otra funcion que hay que programar. 

La tabla categoria yo la puedo llenar en ese Script manualmente pero la relacion desde producto se debe  hacer al momento de hacer el insert que el formulario de registrar producto tenga un select para escoger la categoria eso ya lo harias ene l momento de cargar el dropdownlist como dices con el select pero para el insert es una funcion diferente. Si me entiende? el dropdownlist lo vas a cargar dinamicamente sin recargar la pagina o como lo vas hacer porque eso lo debes tener en cuenta para el insert.

**Comment by lramirezsuarez** [comment]
Si, ya esta. Con CategId y CustomId, ya estan funcionando, yo los agregue a mi base de datos.
Como te digo, solo falta agregar o llamar el customerId, el categoryID ya lo cuadro yo cuando agregue el Select de categorias.

**Comment by rubberydev** [comment]
A listo parce 👍 excelente trabajo ya lo que falta son detallitos.
